### ISSUE TITLE
Readme organisation 

### ISSUE THREAD

**Issue by swiftdiaries** [CiscoAI/cisco-kubeflow-starter-pack#10]
As an end-user, this is my current walkthrough  for the starter-pack
Steps:
- visit main readme
- go to install page
- come back to main readme
- go to apps page
- go to specific vertical

Proposed walkthrough:
- visit main readme
- if k8s installed, go to apps page
- if k8s is not installed, go to install page
- from install page link to apps page

cc @elviraux @amsaha

**Comment by amsaha** [comment]
Installation has both k8s and kubeflow. so the proposed walkthrough has to be a bit more nuanced.

**Comment by krishnadurai** [comment]
@swiftdiaries How much is #11 linked to this issue?

**Comment by amsaha** [comment]
BTW, whatever be the reorganization, try and avoid links from directories to other directories and even to the root directory. Any future reorganizations will break such links. @elviraux  @swiftdiaries

**Comment by ramdootp** [comment]
Is there an agreement on which walkthrough we want to adopt @amsaha @krishnadurai 
There will be changes reqd. in vertical Readme whichever way is adopted

**Comment by swiftdiaries** [comment]
I think we can keep the existing ones.
> Any future reorganizations will break such links

I hadn't considered this

**Comment by ramdootp** [comment]
> BTW, whatever be the reorganization, try and avoid links from directories to other directories and even to the root directory. Any future reorganizations will break such links. @elviraux @swiftdiaries

Not sure if its absolutely possible to avoid cross referencing

**Comment by amsaha** [comment]
Yeah, not always possible. Hence minimize.

**Comment by amsaha** [comment]
@ramdootp @swiftdiaries should we close this now or is someone working on this?

**Comment by amsaha** [comment]
We will close this now. Will revisit later if needed. Readme improvements will anyway be a continuous process.
