### ISSUE TITLE
Issue when trying to run the 'COVID-19 Forecasting using Kubeflow Pipelines'

### ISSUE THREAD

**Issue by musadiq1** [CiscoAI/cisco-kubeflow-starter-pack#101]
I'm trying to run the 'COVID-19 Forecasting using Kubeflow Pipelines'. When installing NFS server, I’m getting an error. Do you know how to get past this?

I’m following instructions from https://github.com/CiscoAI/cisco-kubeflow-starter-pack/tree/master/apps/networking/ble-localization/onprem/install#nfs

root@XYZ:~# sudo apt install nfs-kernel-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
nfs-kernel-server is already the newest version (1:1.2.8-9ubuntu12.3).
0 upgraded, 0 newly installed, 0 to remove and 226 not upgraded.
root@XYZ:~# sh nfs-installation.sh
sh: 0: Can't open nfs-installation.sh

**Comment by djscape** [comment]
1. Download folder and files of the path "cisco-kubeflow-starter-pack/apps/networking/ble-localization/onprem/install/".
2. And then move that folder.
3. sh nfs-installation.sh 

When I did above way, I can install containers regarding nfs server on kubernetes.

**Comment by prem0912** [comment]
Updated nfs-installation readme

**Comment by musadiq1** [comment]
Thanks. The provided steps worked. Please update the instructions.

**Comment by swiftdiaries** [comment]
Is this addressed?

**Comment by musadiq1** [comment]
yes this is addressed
