### ISSUE TITLE
Needless line in (sample)BLERSSI Pipeline Deployment in UCS

### ISSUE THREAD

**Issue by sakaia** [CiscoAI/cisco-kubeflow-starter-pack#108]
`component.yaml` file does not exist but it refers on line 124.

‘‘‘bash
tf_train_model_op = kfp.components.load_component_from_file(os.path.join(component_root_train, component_file)) 
tf_train_model_op = kfp.components.load_component_from_file(os.path.join(component_root_train, 'component.yaml')) 
```

Error message is follows

```bash
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-15-a9e91f9ee2da> in <module>
      1 tf_train_model_op = kfp.components.load_component_from_file(os.path.join(component_root_train, component_file))
----> 2 tf_train_model_op = kfp.components.load_component_from_file(os.path.join(component_root_train, 'component.yaml'))
      3 tf_serve_model_op = kfp.components.load_component_from_file(os.path.join(component_root_serve, 'component.yaml'))
      4 tf_webui_op = kfp.components.load_component_from_file(os.path.join(component_root_webui, 'component.yaml'))
      5 tf_tensor_op = kfp.components.load_component_from_file(os.path.join(component_root_tensorboard, 'component.yaml'))

/usr/local/lib/python3.6/dist-packages/kfp/components/_components.py in load_component_from_file(filename)
    103     if filename is None:
    104         raise TypeError
--> 105     with open(filename, 'rb') as component_stream:
    106         return _load_component_from_yaml_or_zip_stream(component_stream, filename)
    107 

FileNotFoundError: [Errno 2] No such file or directory: 'cisco-kubeflow-starter-pack/apps/networking/ble-localization/onprem/pipelines/components/v2/tf-model-train/component.yaml'
```

It should remove following line.

https://github.com/CiscoAI/cisco-kubeflow-starter-pack/blame/master/apps/networking/ble-localization/onprem/pipelines/BLERSSI-Pipeline-Deployment.ipynb#L124

**Comment by swiftdiaries** [comment]
Hey @sakaia !
Thank you for opening an issue. 
This is fixed in the [dev branch](https://github.com/CiscoAI/cisco-kubeflow-starter-pack/blob/dev/apps/networking/ble-localization/onprem/pipelines/BLERSSI-Pipeline-Deployment.ipynb). Please use that in the interim before it gets merged onto master for the next release. Would that be an acceptable solution?

**Comment by ramdootp** [comment]
dev branch is merged to master. Fix is available in master
