### ISSUE TITLE
While running ble-localization app on UCS, I'm getting FileNotFoundError: [Errno 2] No such file or directory: 'cisco-kubeflow-starter-pack/apps/networking/ble-localization/onprem/pipelines/components/v2/tf-model-train/component.yaml'

### ISSUE THREAD

**Issue by musadiq1** [CiscoAI/cisco-kubeflow-starter-pack#111]
Getting the following error:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-a9e91f9ee2da> in <module>
      1 tf_train_model_op = kfp.components.load_component_from_file(os.path.join(component_root_train, component_file))
----> 2 tf_train_model_op = kfp.components.load_component_from_file(os.path.join(component_root_train, 'component.yaml'))
      3 tf_serve_model_op = kfp.components.load_component_from_file(os.path.join(component_root_serve, 'component.yaml'))
      4 tf_webui_op = kfp.components.load_component_from_file(os.path.join(component_root_webui, 'component.yaml'))
      5 tf_tensor_op = kfp.components.load_component_from_file(os.path.join(component_root_tensorboard, 'component.yaml'))

~/.local/lib/python3.6/site-packages/kfp/components/_components.py in load_component_from_file(filename)
     96         Once called with the required arguments, the factory constructs a pipeline task instance (ContainerOp).
     97     '''
---> 98     component_spec = _load_component_spec_from_file(path=filename)
     99     return _create_task_factory_from_component_spec(
    100         component_spec=component_spec,

~/.local/lib/python3.6/site-packages/kfp/components/_components.py in _load_component_spec_from_file(path)
    129 
    130 def _load_component_spec_from_file(path) -> ComponentSpec:
--> 131     with open(path, 'rb') as component_stream:
    132         return _load_component_spec_from_yaml_or_zip_stream(component_stream)
    133 

FileNotFoundError: [Errno 2] No such file or directory: 'cisco-kubeflow-starter-pack/apps/networking/ble-localization/onprem/pipelines/components/v2/tf-model-train/component.yaml'

I'm getting the above error while running the cell:
tf_train_model_op = kfp.components.load_component_from_file(os.path.join(component_root_train, component_file)) 
tf_train_model_op = kfp.components.load_component_from_file(os.path.join(component_root_train, 'component.yaml')) 
tf_serve_model_op = kfp.components.load_component_from_file(os.path.join(component_root_serve, 'component.yaml'))
tf_webui_op = kfp.components.load_component_from_file(os.path.join(component_root_webui, 'component.yaml'))
tf_tensor_op = kfp.components.load_component_from_file(os.path.join(component_root_tensorboard, 'component.yaml'))

! git clone https://github.com/CiscoAI/cisco-kubeflow-starter-pack.git

As shown in the screenshot, the file **tf-model-train/component.yaml** is missing under **cisco-kubeflow-starter-packappsnetworkingble-localizationonprempipelinescomponentsv2tf-model-train
<img width="1185" alt="Screen Shot 2020-07-16 at 4 23 56 PM" src="https://user-images.githubusercontent.com/66083851/87732090-de725e80-c780-11ea-9912-7f3cfadcef69.png">
**

**Comment by sravi999** [comment]
Hi @musadiq1 
This issue is fixed in [dev branch](https://github.com/CiscoAI/cisco-kubeflow-starter-pack/blob/dev/apps/networking/ble-localization/onprem/pipelines/BLERSSI-Pipeline-Deployment.ipynb). Could you please use it from **dev branch**

**Comment by ramdootp** [comment]
dev branch is merged to master. The fix is available in master now.
