### ISSUE TITLE
Install kubeflow throwing 404 Error.

### ISSUE THREAD

**Issue by sravi999** [CiscoAI/cisco-kubeflow-starter-pack#37]
[kubeflow.sh](https://github.com/CiscoAI/cisco-kubeflow-starter-pack/blob/master/install/kubeflowup.sh) throwing 404 Not Found Error.

samba@ubuntu:~/repo/starter_pack/cisco-kubeflow-starter-pack/install$ bash kubeflowup.sh
--2020-04-02 05:05:56--  https://github.com/kubeflow/kfctl/releases/download/v1.0/kfctl_v1.0-0-g94c35cf_linux.tar.gz%0D%0D
Resolving github.com (github.com)... 13.234.176.102
Connecting to github.com (github.com)|13.234.176.102|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-02 05:05:57 ERROR 404: Not Found.

tar (child): kfctl.tar.gz\r: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
chmod: cannot access 'kfctl'$'\r': No such file or directory
--2020-04-02 05:05:57--  https://raw.githubusercontent.com/kubeflow/manifests/v1.0.0/kfdef/kfctl_k8s_istio.v1.0.0.yaml%0D%0D
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-02 05:05:58 ERROR 404: Not Found.

kubeflowup.sh: line 11: ./kfctl: No such file or directory
The Kubeflow Central Dashboard is at :31380

**Comment by amsaha** [comment]
Fixed via #38
