### ISSUE TITLE
Readme enhancements for hybrid demo

### ISSUE THREAD

**Issue by johnugeorge** [CiscoAI/cisco-kubeflow-starter-pack#79]
1.  Since custom python packages are not installed by default, command to be included  for pip installation. ( kfp boto3 pandas sagemaker mxnet)

2. Currently, instructions are included in Readme but not in notebook. Readme instructions and notebook have to be in sync. Else, user might find it difficult when someone runs the notebook cells directly.

3. Is it better to remove the while loop in the notebook and give instructions to check status and wait till endpoint is in service ? Else, user might not understand the control when kernel is in while loop for > 10 min. 

4. We need to ensure that notebook is restartable. i.e., if components are created already, skip them and continue to the next.(Instead of duplicating and wasting resources )

5.  Is there best way to add env variables without exposing  key and secret directly inside the notebook.

5. Need to verify when user provides custom values to configurable variables in the notebook. Eg: It didn't work for me when my s3 bucket was created on a different region though region is configurable in the notebook code(default is us-west-2).

**Comment by prem0912** [comment]
1,2,3 and 5 addressed and created Pull

4. This can be achieved by removing timestamp from endpoint name. But we need to provide new endpoint name each time while running the notebook else it will throw error.

6. Working on it

**Comment by swiftdiaries** [comment]
For 6, the region has to be uniform throughout the pipeline.
Bucket, SageMaker components. It's a requirement from the SageMaker API.
We should message that better in the README.

**Comment by amsaha** [comment]
What is the status of this? Can this be closed?

**Comment by prem0912** [comment]
All the issues resolved. we can close this issue
